[application]

[web.app]

# HTML title tag content
title = "polyblade"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "lgbt.vera.polyblade"
publisher = "Vera Gonzalez"
icon = ["assets/logo.png"]
category = "Graphics"
short_description = "Make shapes dance."
long_description = "A cross-platform application for visualizing and animating Conway polyhedron operations."
copyright = "Copyright © 2026 Vera Gonzalez"
