app = 'polyblade-app'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']
  grace_period = "10s"
  timeout = "500s"


[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
